server:
  port: 9000

spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/user-db}
    username: ${DB_USERNAME:review}
    password: ${DB_PASSWORD:rating}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Logging configuration
logging:
  level:
    org.springframework.data.mongodb: DEBUG